# Generated by Django 5.1.1 on 2024-10-31 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('rating', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.CharField(blank=True, max_length=25)),
                ('rated', models.CharField(blank=True, max_length=10)),
                ('released', models.CharField(blank=True, max_length=25)),
                ('runtime', models.CharField(blank=True, max_length=25)),
                ('director', models.CharField(blank=True, max_length=100)),
                ('writer', models.CharField(blank=True, max_length=300)),
                ('plot', models.CharField(blank=True, max_length=900)),
                ('language', models.CharField(blank=True, max_length=300)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('awards', models.CharField(blank=True, max_length=200)),
                ('poster', models.ImageField(blank=True, upload_to='movies')),
                ('poster_url', models.URLField(blank=True)),
                ('metascore', models.CharField(blank=True, max_length=5)),
                ('imdb_rating', models.CharField(blank=True, max_length=5)),
                ('imdb_votes', models.CharField(blank=True, max_length=100)),
                ('imdb_id', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(blank=True, max_length=10)),
                ('actors', models.ManyToManyField(blank=True, to='actor.actor')),
                ('genre', models.ManyToManyField(blank=True, to='movie.genre')),
                ('ratings', models.ManyToManyField(blank=True, to='movie.rating')),
            ],
        ),
    ]
